### ISSUE TITLE
Events sent from CEP to Orion fail with XML parser error

### ISSUE THREAD

**Issue by manubaum** [Orange-OpenSource/fiware-cepheus#23]
Running the following example: 
https://fiware-cepheus.readthedocs.org/en/latest/examples/4_CepAndBrokerAndOrion/index.html

Used components:
cepheus-cep/broker: latest
orion: latest deb package

Problem: 
Events resulting from the CEP (and forwarded to Orion) fail (see details in request/response) below. Strangely, orion returns http status 200, even though the content indicates, that the request failed. Other unrelated request sent to orion with updateAction=APPEND do work though.

HTTP Request from cepheus-CEP to Orion
------------------------------------------------------------------------
POST /ngsi10/updateContext HTTP/1.1
Accept: application/xml
Content-Type: application/xml
Content-Length: 403
Host: localhost:1026
Connection: Keep-Alive
User-Agent: Apache-HttpAsyncClient/4.1 (Java/1.8.0_65)
```XML
<updateContextRequest><updateAction>UPDATE</updateAction><contextElementList><contextElement><entityId type="Floor" isPattern="false"><id>Floor3</id></entityId><contextAttributeList><contextAttribute><name>temperature</name><type>double</type><contextValue>23.46153846153846</contextValue><metadata/></contextAttribute></contextAttributeList></contextElement></contextElementList></updateContextRequest>
```

HTTP Request from Orion
------------------------------------------------------------------------
HTTP/1.1 200 OK
Content-Length: 126
Content-Type: application/xml
Date: Thu, 12 Nov 2015 17:17:45 GMT

```XML
<orionError>
  <code>400</code>
  <reasonPhrase>Bad Request</reasonPhrase>
  <details>XML Parse Error</details>
</orionError>
```

**Comment by marcc-orange** [comment]
Orion expects the Context Entity and its attributes to exist, by having been previously added to Orion by an APPEND or registerContext request, when using `UPDATE`.

We just recently changed our [examples](https://github.com/Orange-OpenSource/fiware-cepheus/commit/d7a82588ca3cf89983069def20f76a33a2a8311d) and [code](https://github.com/Orange-OpenSource/fiware-cepheus/commit/980f59014ca379fc7890caf55e976050ae7cc968) to use `APPEND` instead of `UPDATE` as we also hit this error.

So the latest version (0.1.2-SNAPSHOT from `master` branch) examples and code should work fine with Orion.

> Strangely, orion returns http status 200, even though the content indicates, that the request failed.

This is expected from Orion as this behavior is specified as part of the NGSI v1 protocol specification. All NGSI requests will always return `200 Ok` HTTP response code, applications are expected to check for `errorCode` and `statusCode` tags in the response.

What is unexpected is the `orionError` tag which are not part of the NGSI v1 specification.

Can you confirm you still get the error once you use `UPDATE` with an existing Context Entity, I tried to reproduce with Postman on `orion.lab.fiware.org:1026` but got no error:

```
POST /ngsi10/updateContext HTTP/1.1
Host: orion.lab.fiware.org:1026
Accept: application/xml
X-Auth-Token: **********************************
Content-Type: application/xml
Cache-Control: no-cache

<updateContextRequest><updateAction>UPDATE</updateAction><contextElementList><contextElement><entityId type="Floor" isPattern="false"><id>Floor3</id></entityId><contextAttributeList><contextAttribute><name>temperature</name><type>double</type><contextValue>23.46153846153846</contextValue><metadata/></contextAttribute></contextAttributeList></contextElement></contextElementList></updateContextRequest>
```

response :

```
<updateContextResponse>
    <contextResponseList>
        <contextElementResponse>
            <contextElement>
                <entityId type="Floor" isPattern="false">
                    <id>Floor3</id>
                </entityId>
                <contextAttributeList>
                    <contextAttribute>
                        <name>temperature</name>
                        <type>double</type>
                        <contextValue></contextValue>
                    </contextAttribute>
                </contextAttributeList>
            </contextElement>
            <statusCode>
                <code>200</code>
                <reasonPhrase>OK</reasonPhrase>
            </statusCode>
        </contextElementResponse>
    </contextResponseList>
</updateContextResponse>
```

**Comment by manubaum** [comment]
Hi Mark. Thanks for the hint with the UPDATE/APPEND. With the latest cepheus we see it working now. Also thanks for the hint reg. http status 200/400. Regarding the orion Error tag, we just opened an issue reg. that: https://github.com/telefonicaid/fiware-orion/issues/1500
