### ISSUE TITLE
Exception logging

### ISSUE THREAD

**Issue by chazemar** [Orange-OpenSource/fiware-cepheus#56]
Please,
Can you improve exception logging by print stacktrace and not only Exception name ?
Thanks.

**Comment by marcc-orange** [comment]
We decided _not_ to print stacktraces in default log levels (error/warn levels) for most common logged errors on requests (updateContext, registrations, etc...) as most of the time they _should_ be caused by runtime errors like timeouts or network errors.

Adding logs with debug level with full stacktraces would surely make a nice addition.
